services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - MAX_CONTENT_LENGTH=16777216  # 16MB em bytes
    restart: unless-stopped